### ISSUE TITLE
x/forwarding: bizarre and unexplained error handling to swallow up errors and return nil inside Decorator.CheckMessages

### ISSUE THREAD

**Issue by odeke-em** [noble-assets/noble#314]
Just while auditing this code I noticed this strange pattern of returning a nil error even after encountering a prior error
![image](https://github.com/noble-assets/noble/assets/4898263/4cb722bc-57ff-4adc-9153-1e4c0643e64c)

https://github.com/noble-assets/noble/blob/d809e7e4111782a9f349d29599a1d4ffb2cdb698/x/forwarding/ante.go#L42-L45 

https://github.com/noble-assets/noble/blob/d809e7e4111782a9f349d29599a1d4ffb2cdb698/x/forwarding/ante.go#L51-L71

The above do look really off and don't have any explanations for why they are like that; it also would mean that if intentional, there should be tests to that effect to assert these conditions

**Comment by johnletey** [comment]
Thanks for your feedback here @odeke-em!

The reason why it's implemented like this, is because we'd prefer all errors to be handled by the `x/cctp` module directly, and not by this new module. Therefore, if we encounter an error, we simply don't check the account against the forwarding state.
