### ISSUE TITLE
x/tokenfactory/keeper: unexpected inconsistency mixing non-gRPC errors without a status+ code in an area with gRPC errors

### ISSUE THREAD

**Issue by odeke-em** [noble-assets/noble#316]
This code is quite inconsistent when an error is encountered while parsing an address https://github.com/noble-assets/noble/blob/main/x/tokenfactory/keeper/grpc_query_blacklisted.go#L49-L52

![image](https://github.com/noble-assets/noble/assets/4898263/95d86083-3e0f-4fe4-8c7c-c01a96f607b9)

and also inside Keeper.Mint https://github.com/noble-assets/noble/blob/d809e7e4111782a9f349d29599a1d4ffb2cdb698/x/tokenfactory/keeper/msg_server_mint.go#L35-L37 in an area where errors are being wrapped and sent over with a status code

## Remedy
Use status codes to wrap that error with a code of InvalidArgument and please add a test for invalid addresses because the presence of that error not being caught means that the other RPC is going to encounter an unexpected error or could even crash

**Comment by johnletey** [comment]
Thanks for your issue @odeke-em, however, our team has deprecated the TokenFactory module as of v8!
