### ISSUE TITLE
Intermittent failure to load state

### ISSUE THREAD

**Issue by agouin** [noble-assets/noble#33]
When this happens, the chain validators are producing blocks fine, but the state cannot be queried, so operations such as queries, tx broadcasts, and state exports all fail.

```
exit code 1:  Error: rpc error: code = InvalidArgument desc = failed to load state at height 7; version does not exist (latest height: 7): invalid request
```

This happens when running queries against a prior height (non-latest) also.

This can be reproduced in the ibctest case [here](https://github.com/strangelove-ventures/noble/blob/feat/ibctest/ibctest/ibctest_test.go), but has also been reproduced outside of ibctest

**Comment by jtieri** [comment]
This has been fixed as of #40
