### ISSUE TITLE
Support of Multiple Minting Denominations

### ISSUE THREAD

**Issue by cxyzhang0** [noble-assets/noble#343]
Hi, there may be use cases where the tokenfactory is expected to mint fungible tokens of different denominations.  What do people think about extending TF to support such use cases? Is a PR desired?

Thanks.

\Sean

**Comment by johnletey** [comment]
Thanks for your issue @cxyzhang0! For now, we have no plans on updating the TokenFactory and FiatTokenFactory design to support multiple denominations. Closing this for now 😄
