### ISSUE TITLE
v4.0.0 failed to build

### ISSUE THREAD

**Issue by RiteshUdasi1234** [noble-assets/noble#347]
=> ERROR [build 7/7] RUN make build                                                                                                                   32.8s
------
 > [build 7/7] RUN make build:
#0 0.856 go build -tags "netgo muslc" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=noble -X github.com/cosmos/cosmos-sdk/version.AppName=nobled -X github.com/cosmos/cosmos-sdk/version.Version=4.0.0 -X github.com/cosmos/cosmos-sdk/version.Commit=28bc842ed691e6a7ecf284177fe1e7284f5678b3 -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo muslc," -X github.com/tendermint/tendermint/version.TMCoreSemVer=v0.34.27' -o bin/nobled ./cmd/nobled
#0 17.58 # github.com/ethereum/go-ethereum/crypto/secp256k1
#0 17.58 cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in $PATH
#0 31.46 make: *** [Makefile:85: build] Error 1
------
Dockerfile:18
--------------------
  16 |     ARG TARGETARCH TARGETOS
  17 |     ENV GOOS=${TARGETOS} GOARCH=${TARGETARCH} LEDGER_ENABLED=false BUILD_TAGS=muslc
  18 | >>> RUN make build
  19 |
  20 |     FROM alpine:latest
--------------------
ERROR: failed to solve: process "/bin/sh -c make build" did not complete successfully: exit code: 2

**Comment by johnletey** [comment]
@RiteshUdasi1234 Please try to build the latest release of Noble (`v4.1.3`). If this issue persists, please feel free to reopen.
