### ISSUE TITLE
Add support for bech32m

### ISSUE THREAD

**Issue by liangping** [noble-assets/noble#354]
We are trying to transfer `uusdc` to Bitcoin compatible address(bech32 style) on our blockchain, we got following error:

```
// noble
{
  "chainId": "grand-1",
  "txBody": {
    "extensionOptions": [],
    "memo": "",
    "messages": [
      {
        "typeUrl": "/ibc.applications.transfer.v1.MsgTransfer",
        "value": {
          "memo": "",
          "receiver": "bc1qugrutza3gjwkh22yg486kyjhwt4f9a0rtdhqmf",
          "sender": "noble1t4yy99hwsv7rr2z32z0cul5vd7w2jm0sgcweak",
          "sourceChannel": "channel-155",
          "sourcePort": "transfer",
          "timeoutTimestamp": "1713518098231000000",
          "token": {
            "amount": "500000",
            "denom": "uusdc"
          }
        }
      }
    ],
    "nonCriticalExtensionOptions": [],
    "timeoutHeight": "0"
  }
}
```

Error：
```
{
  "tx_response": {
    "height": "0",
    "txhash": "260B8176E3ED3A01204CE7FF1C5B32D37EA2658B3612D6B0FC40B832257E4C3D",
    "codespace": "undefined",
    "code": 1,
    "data": "",
    "raw_log": "error decoding address (bc1qugrutza3gjwkh22yg486kyjhwt4f9a0rtdhqmf): decoding bech32 failed: invalid incomplete group",
    "logs": [
    ],
    "info": "",
    "gas_wanted": "0",
    "gas_used": "0",
    "tx": null,
    "timestamp": "",
    "events": [
    ]
  }
}
```

Why noble decode the receiver address of IBC transfer transaction. Is it possible to improve it to support both bech32 and bech32m. 

Note: This address work fine on other blockchains.

**Comment by faddat** [comment]
Because it is safer that way.

Since noble decodes the bech32 addresses, it is not vulnerable to p2p storms, and probably other stuff.

**Comment by boojamya** [comment]
This is being triggered via the ibc [blocklist](https://github.com/circlefin/noble-fiattokenfactory/blob/master/x/blockibc/blockibc.go).

We do plan on adding support for bech32m addresses in future which should solve this issue.

**Comment by liangping** [comment]
@boojamya. That's awesome!

**Comment by johnletey** [comment]
This has been implemented in the latest upgrade of Circle's FiatTokenFactory module!
https://github.com/circlefin/noble-fiattokenfactory/commit/c20bd0c8442fa9b70dc88d8648a5e337c66d4644

Launching on testnet later tonight and mainnet immanently 😄
