### ISSUE TITLE
v4..0.3 to v4.1.3

### ISSUE THREAD

**Issue by RiteshUdasi1234** [noble-assets/noble#378]
@johnletey @boojamya I am on version 4.0.3
Trying to sync my node using the ready image, but i am facing peers sync issue -

id=3c191ee9e9ff2c11cecde57d646677e711ab509c id=3c191ee9e9ff2c11cecde57d646677e711ab509c ip=34.88.159.55 id=3c191ee9e9ff2c11cecde57d646677e711ab509c id=3c191ee9e9ff2c11cecde57d646677e711ab509c ip=34.88.159.55 port=26656
12:54AM INF service stop impl=module=p2p msg=peer=
Data=[object Object] Data=[object Object] Logger=[object Object]
12:54AM ERR Stopping peer for error err=EOF module=p2p peer=
Data=[object Object] Data=[object Object] Logger=[object Object]

id=3c191ee9e9ff2c11cecde57d646677e711ab509c id=3c191ee9e9ff2c11cecde57d646677e711ab509c ip=34.88.159.55 id=3c191ee9e9ff2c11cecde57d646677e711ab509c id=3c191ee9e9ff2c11cecde57d646677e711ab509c ip=34.88.159.55 port=26656
12:54AM INF service stop impl=module=p2p msg=peer=
12:54AM INF invalid peer blockHeight=3669415 module=blockchain peer=7cf6f88a5c5af2ec101072d7ad766bbc5ab026d2
Data=[object Object] Data=[object Object] Logger=[object Object]
12:54AM ERR Stopping peer for error err="error with peer 7cf6f88a5c5af2ec101072d7ad766bbc5ab026d2: invalid peer" module=p2p peer=
Logger=[object Object]

id=7cf6f88a5c5af2ec101072d7ad766bbc5ab026d2 id=7cf6f88a5c5af2ec101072d7ad766bbc5ab026d2 ip=185.225.191.100 id=7cf6f88a5c5af2ec101072d7ad766bbc5ab026d2 id=7cf6f88a5c5af2ec101072d7ad766bbc5ab026d2 ip=185.225.191.100 port=26656
12:54AM INF service stop impl=module=p2p msg=peer=
Data=[object Object] Data=[object Object] Logger=[object Object]

id=7cf6f88a5c5af2ec101072d7ad766bbc5ab026d2 id=7cf6f88a5c5af2ec101072d7ad766bbc5ab026d2 ip=185.225.191.100 id=7cf6f88a5c5af2ec101072d7ad766bbc5ab026d2 id=7cf6f88a5c5af2ec101072d7ad766bbc5ab026d2 ip=185.225.191.100 port=26656
12:54AM INF service stop impl=module=p2p msg=peer=
12:55AM INF Saving AddrBook to file book=/noble/.noble/config/addrbook.json module=p2p size=191
12:55AM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=2 numToDial=8
Data=[object Object] Data=[object Object] Logger=[object Object]
12:55AM INF We need more addresses. Sending pexRequest to random peer module=pex peer=

id=afb6bc227f15553a0e8fed6adced7cac259cd378 id=afb6bc227f15553a0e8fed6adced7cac259cd378 ip=146.190.222.171 id=afb6bc227f15553a0e8fed6adced7cac259cd378 id=afb6bc227f15553a0e8fed6adced7cac259cd378 ip=146.190.222.171 port=26656
12:55AM INF service start impl="Peer{MConn{146.190.222.171:26656} afb6bc227f15553a0e8fed6adced7cac259cd378 out}" module=p2p msg=peer=

id=afb6bc227f15553a0e8fed6adced7cac259cd378 id=afb6bc227f15553a0e8fed6adced7cac259cd378 ip=146.190.222.171 id=afb6bc227f15553a0e8fed6adced7cac259cd378 id=afb6bc227f15553a0e8fed6adced7cac259cd378 ip=146.190.222.171 port=26656
12:55AM INF service start impl=MConn{146.190.222.171:26656} module=p2p msg=peer=
Logger=[object Object]
id=afb6bc227f15553a0e8fed6adced7cac259cd378 id=afb6bc227f15553a0e8fed6adced7cac259cd378 ip=146.190.222.171 id=afb6bc227f15553a0e8fed6adced7cac259cd378 id=afb6bc227f15553a0e8fed6adced7cac259cd378 ip=146.190.222.171 port=26656
12:55AM INF Connection is closed @ recvRoutine (likely by the other side) conn=module=p2p peer=
Logger=[object Object]

id=afb6bc227f15553a0e8fed6adced7cac259cd378 id=afb6bc227f15553a0e8fed6adced7cac259cd378 ip=146.190.222.171 id=afb6bc227f15553a0e8fed6adced7cac259cd378 id=afb6bc227f15553a0e8fed6adced7cac259cd378 ip=146.190.222.171 port=26656
12:55AM INF service stop impl=module=p2p msg=peer=
Data=[object Object] Data=[object Object] Logger=[object Object]
12:55AM ERR Stopping peer for error err=EOF module=p2p peer=
Data=[object Object] Data=[object Object] Logger=[object Object]

id=afb6bc227f15553a0e8fed6adced7cac259cd378 id=afb6bc227f15553a0e8fed6adced7cac259cd378 ip=146.190.222.171 id=afb6bc227f15553a0e8fed6adced7cac259cd378 id=afb6bc227f15553a0e8fed6adced7cac259cd378 ip=146.190.222.171 port=26656
12:55AM INF service stop impl=module=p2p msg=peer=

id=d82bd95eaf518bafc209b663c35a73853e3eab7a id=d82bd95eaf518bafc209b663c35a73853e3eab7a ip=194.233.93.126 id=d82bd95eaf518bafc209b663c35a73853e3eab7a id=d82bd95eaf518bafc209b663c35a73853e3eab7a ip=194.233.93.126 port=26656
12:55AM INF service start impl="Peer{MConn{194.233.93.126:26656} d82bd95eaf518bafc209b663c35a73853e3eab7a out}" module=p2p msg=peer=

id=d82bd95eaf518bafc209b663c35a73853e3eab7a id=d82bd95eaf518bafc209b663c35a73853e3eab7a ip=194.233.93.126 id=d82bd95eaf518bafc209b663c35a73853e3eab7a id=d82bd95eaf518bafc209b663c35a73853e3eab7a ip=194.233.93.126 port=26656
12:55AM INF service start impl=MConn{194.233.93.126:26656} module=p2p msg=peer=
12:55AM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=3 numToDial=7
Data=[object Object] Data=[object Object] Logger=[object Object]
12:55AM INF We need more addresses. Sending pexRequest to random peer module=pex peer=

This is my docker compose file -
services:
    noble-node:
        volumes:
            - '/ThirdDisk122Machine/node_noble_new/noble/.noble:/noble/.noble'
        command:
            - 'nobled'
            - 'start'
            - '--pruning'
            - 'nothing'
            - '--home'
            - '/noble/.noble'
        ports:
            - '2332:26657'
            - '4332:26656'
            - '5332:1317'
        image: 'ghcr.io/noble-assets/noble:v4.0.3'
        environment:
            self_hostname: 0.0.0.0

**Comment by boojamya** [comment]
What peers and seeds are you using/where did you get them?

Try using these peers with no seeds in your config.toml:

`"3402e50ad4d838b26f8341a956c7b4b8a3c61ee5@65.109.93.44:21556, 08d9b0fd3d4407a5f141f383fde6f32c06f95134@159.89.21.233:30192, afb6bc227f15553a0e8fed6adced7cac259cd378@146.190.222.171:26656"`

Note: in my experience this process can take a few minutes so let it run for a bit.

**Comment by RiteshUdasi1234** [comment]
I did not get these peers and seeds from anywhere -
I just brought my container up and the node started but it was not syncing and looking for peers only -
![image](https://github.com/noble-assets/noble/assets/50057308/2cf04164-fd44-4c52-873d-8cf49163d1d4)
See this is the folder structure I have and the image that I am using is -
'ghcr.io/noble-assets/noble:v4.0.3'

And this is my docker compose file -
services:
    noble-node:
        volumes:
            - '/{DiskName}/node_noble_new/noble/.noble:/noble/.noble'
        command:
            - 'nobled'
            - 'start'
            - '--pruning'
            - 'nothing'
            - '--home'
            - '/noble/.noble'
        ports:
            - '2332:26657'
            - '4332:26656'
            - '5332:1317'
        image: 'ghcr.io/noble-assets/noble:v4.0.3'
        environment:
            self_hostname: 0.0.0.0

**Comment by RiteshUdasi1234** [comment]
@boojamya @johnletey 
I need the docker file for the latest version, I am trying to use docker for running node
I see that v3.0.0 last had the docker file in your repo.
Could you please provide me the latest docker file, as I am facing issues while the building the image.

**Comment by boojamya** [comment]
Not sure why you are just seeing v3.0.0. All mainnet tagged versions are available in our repo:
https://github.com/noble-assets/noble/pkgs/container/noble/versions?filters%5Bversion_type%5D=tagged&page=2

As of writing this `v4.1.3` is latest.
docker package: https://github.com/noble-assets/noble/pkgs/container/noble/214611137?tag=v4.1.3

**Comment by RiteshUdasi1234** [comment]
@boojamya @jonathanpberger 
Now I am trying to sync the node from scratch from v1.0.0
Can you please share with me the list of peers and seeds to use for every version
Because with the peers you gave, the v1.0.0 is not syncing

Here are the steps I am performing to setup my node from scratch -

sudo git clone https://github.com/strangelove-ventures/noble  noble
cd noble
git checkout v1.0.0

sudo docker build -t nobleimage:v1.0.0 .

Initialize Chain
sudo docker run -it -p 2332:26657 -p 4332:26656 -v /{DiskName}/node-noble/noble/.noble:/noble/.noble noble:1.0.0 nobled init noblemoniker --chain-id noble-1

Download Genesis
sudo wget -O genesis.json https://snapshots.polkachu.com/genesis/noble/genesis.json  --inet4-only
mv genesis.json .noble/config

Configure Seed - In this I am adding the peers you shared for in the config.toml file in persistant_peers = ""

AddrBook
wget -O addrbook.json https://snapshots.polkachu.com/addrbook/noble/addrbook.json  --inet4-only
mv addrbook.json .noble/config
From https://polkachu.com/addrbooks/noble 

Start Node
sudo docker run -d -it -p 2332:26657 -p 4332:26656 -p 5332:1317 -v /{DiskName}/node-noble/noble/.noble:/noble/.noble noble:1.0.0 nobled start --pruning nothing

AFTER ALL THESE STEPS, THE NODE SHOULD START SYNCING, but its not
My logs - 
6:18PM INF We need more addresses. Sending pexRequest to random peer module=pex peer=
6:19PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=7 numToDial=3
Data={} Logger={}
6:19PM INF We need more addresses. Sending pexRequest to random peer module=pex peer=
6:19PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=7 numToDial=3
Data={} Logger={}
6:19PM INF We need more addresses. Sending pexRequest to random peer module=pex peer=
6:20PM INF Saving AddrBook to file book=/noble/.noble/config/addrbook.json module=p2p size=242
6:20PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=7 numToDial=3
Data={} Logger={}
6:20PM INF We need more addresses. Sending pexRequest to random peer module=pex peer=


@boojamya please help me where I am going wrong or what should be the change in my node setup process...
Your quick response would be highly appreciated

**Comment by boojamya** [comment]
I've confirmed that these two peers are valid:

"3402e50ad4d838b26f8341a956c7b4b8a3c61ee5@65.109.93.44:21556, afb6bc227f15553a0e8fed6adced7cac259cd378@146.190.222.171:26656"

It is normal to get the peer logs you posted above at first. 
They should clear up as the connection is established and you address book is populated. Let your node run for  ~ 30min.
