### ISSUE TITLE
Upgrade from v4.1.3 to v.5.0.0

### ISSUE THREAD

**Issue by RiteshUdasi1234** [noble-assets/noble#390]
Hey @johnletey @boojamya ,

Wanted to know if I need to set the --halt-height before upgrading to v5.0.0.
If yes then could you please share the halt height for this upgrade.

This link - "https://docs.nobleassets.xyz/network/upgrades" which you guys shared earlier has STOPPED WORKING now where I could verify the halt heights for all the upgrades with full upgrade path and notes.
So could you please share the new link where I can get these details!

Thanks,
Ritesh

**Comment by boojamya** [comment]
We recently updated our domain from nobleassets.xyz to noble.xyz. Please use: https://docs.noble.xyz/network/upgrades.

You do not need to add a halt height. This was proposed on chain.
