### ISSUE TITLE
Cannot IBC 100+ USDY to Penumbra

### ISSUE THREAD

**Issue by UnityChaos** [noble-assets/noble#404]
Appears to be a bug once total raw amount goes over 10^20 due to 18 decimals on USDY.

![Screenshot from 2024-09-03 13-45-27](https://github.com/user-attachments/assets/a010f361-8195-4a30-8702-024e10ce8a07)

**Comment by johnletey** [comment]
What message are you attempting to execute?

**Comment by zmanian** [comment]
I'm 90% sure that this happening during a call to simulate tx here. 

https://github.com/penumbra-zone/web/blob/1954cea252daf6c9472598c4fc5aaec761c23247/apps/minifront/src/state/ibc-in/index.tsx#L173-L176

**Comment by grod220** [comment]
Here is an example message:

```
{
    "typeUrl": "/ibc.applications.transfer.v1.MsgTransfer",
    "value": {
        "sourcePort": "transfer",
        "sourceChannel": "channel-89",
        "sender": "noble1tnhf37dg646zlr4g54hsp5n2qrchgadk3dzelq",
        "receiver": "penumbracompat11tawd9ru9kvja9wp604zjyq9fu37kh5tmx964deeff0clu35zr69k6k3agmznxz3smszrdcyydpkuepjng06z7arc9akke6aa6njkzrry0car67h5u0chykyjlvwg520e0j83ug",
        "token": {
            "denom": "ausdy",
            "amount": "1.12e+20"
        },
        "timeoutHeight": {
            "revisionNumber": "1",
            "revisionHeight": "944693"
        },
        "timeoutTimestamp": "1725627000000000000",
        "memo": ""
    }
}
```

The cosmjs `SigningStargateClient` is not able to simulate the fee for this transfer 🤔 . It throws precisely [here](https://github.com/penumbra-zone/web/blob/1954cea252daf6c9472598c4fc5aaec761c23247/apps/minifront/src/state/ibc-in/index.tsx#L173).

**Comment by grod220** [comment]
Here is the bug, it's on the penumbra frontend side:
```
   "token": {
            "denom": "ausdy",
            "amount": "1.12e+20"
        },
```

Amount should not be formatted in that way. Can close this here. Will fix on the other end.

**Comment by zmanian** [comment]
This can be closed.

**Comment by johnletey** [comment]
Thanks everyone for trouble shooting, especially @grod220 🙌🏻
