### ISSUE TITLE
Upgrade from v6.0.0 to v.7.0.0

### ISSUE THREAD

**Issue by RiteshUdasi1234** [noble-assets/noble#406]
Hey @johnletey @boojamya ,

Wanted to know if there are any breaking changes or anything we need to know before upgrading to v7.0.0.
Also needed to know if I need to set the --halt-height before upgrading to v7.0.0.
If yes then could you please share the halt height for this upgrade.

This link - "https://docs.noble.xyz/network/upgrades" does not have the halt height details for v7.0.0

Thanks,
Ritesh

**Comment by boojamya** [comment]
Hi @RiteshUdasi1234, this upgrade has been broadcasted on chain. No need to set a halt height, your node will stop automatically.

We'll get the docs site updated ASAP!
Thank you.
